export const restaurant = [
    {
        "id": 1,
        "foodType": "Indian Food",
        "name": "Samosa",
        "price": 20,
        "rating": 4,
        "image": "https://wallpaperaccess.com/full/2069188.jpg",
        "deliveryTime" : 20,
    },
    {
        "id": 2,
        "foodType": "Indian Food",
        "name": "Pav-Bhaji",
        "price": 60,
        "rating": 4,
        "image":"https://cdn.tasteatlas.com//Images/Dishes/f77866f0f5474fc0b41d316f885edcc3.jpg?w=905&h=510",
        "deliveryTime" : 30,
    },
    {
        "id": 3,
        "foodType": "Indian Food",
        "name": "Pakora",
        "price": 20,
        "rating": 4,
        "image":"https://cdn.tasteatlas.com//Images/Dishes/b4deb1913b6b48c2baff9e6cf8d25923.jpg?w=905&h=510",
        "deliveryTime" : 20,
    },
    {
        "id": 4,
        "foodType": "Indian Food",
        "name": "Keema",
        "price": 60,
        "rating": 3,
        "image":"https://cdn.tasteatlas.com//Images/Dishes/aed15b96c6384aef89ce3cefd4e6196d.jpg?w=905&h=510",
        "deliveryTime" : 30,
    },
    {
        "id": 5,
        "foodType": "Indian Food",
        "name": "Dal-Makhani",
        "price": 130,
        "rating": 4,
        "image":"https://cdn.tasteatlas.com//images/dishes/2cbbb8c2a74541c0b03aeaaad7498ca3.jpg?w=905&h=510",
        "deliveryTime" : 30,
    },
    {
        "id": 6,
        "foodType": "Indian Food",
        "name": "Rajma",
        "price": 110,
        "rating": 3,
        "image":"https://www.whiskaffair.com/wp-content/uploads/2019/02/Rajma-Masala-1-3-500x500.jpg",
        "deliveryTime" : 40,
    },
    {
        "id": 7,
        "foodType": "Indian Food",
        "name": "Upma",
        "price": 20,
        "rating": 3,
        "image":"https://cdn.tasteatlas.com//Images/Dishes/e4e3193046014f5bb9d0b6dc838d0f53.jpg?w=905&h=510",
        "deliveryTime" : 20,
    },
    {
        "id": 8,
        "foodType": "Indian Food",
        "name": "Paratha",
        "price": 20,
        "rating": 4,
        "image":"https://cdn.tasteatlas.com//Images/Dishes/7053f1036e63478db68ce8ba7583b39e.jpg?w=905&h=510",
        "deliveryTime" : 20,
    },  
    {
        "id": 9,
        "foodType": "South Indian",
        "name": "Dosa",
        "price": 60,
        "rating": 4,
        "image":"https://www.chefspencil.com/wp-content/uploads/Dosa-1.jpg.webp",
        "deliveryTime" :  30,
    },
    {
        "id": 10,
        "foodType": "South Indian",
        "name": "Idli-Idly",
        "price": 60,
        "rating": 3,
        "image":"https://www.chefspencil.com/wp-content/uploads/Idli.jpg.webp",
        "deliveryTime" : 30,
    },   
    {
        "id": 11,
        "foodType": "South Indian",
        "name": "Puttu",
        "price": 100,
        "rating": 3,
        "image":"https://www.chefspencil.com/wp-content/uploads/Puttu.jpg.webp",
        "deliveryTime" : 30,
    },   
    {
        "id": 12,
        "foodType": "South Indian",
        "name": "Pongal",
        "price": 100,
        "rating": 4,
        "image":"https://www.chefspencil.com/wp-content/uploads/Pongal.jpg.webp",
        "deliveryTime" : 40,
    },   
    {
        "id": 13,
        "foodType": "South Indian",
        "name": "Pesarattu",
        "price": 60,
        "rating": 2,
        "image":"https://www.chefspencil.com/wp-content/uploads/Pesarattu.jpg.webp",
        "deliveryTime" : 20,
    },   
    {
        "id": 14,
        "foodType": "South Indian",
        "name": "Patrode",
        "price": 100,
        "rating": 2,
        "image":"https://www.chefspencil.com/wp-content/uploads/Patrode.jpg.webp",
        "deliveryTime" : 40,
    },     
    {
        "id": 15,
        "foodType": "South Indian",
        "name": "Palkatti",
        "price": 100,
        "rating": 4,
        "image":"https://www.chefspencil.com/wp-content/uploads/Palkatti-Chettinadu.jpg.webp",
        "deliveryTime" : 40,
    },   
    {
        "id": 16,
        "foodType": "Rajasthani Food",
        "name": "Dal-bati",
        "price": 140,
        "rating": 5,
        "image": "https://wp.scoopwhoop.com/wp-content/uploads/2014/09/5677315b6e510a6f3a759a81_1.jpg",
        "deliveryTime" : 30,
    },   
    {
        "id": 17,
        "foodType": "Rajasthani Food",
        "name": "Boondo-Raita",
        "price": 20,
        "rating": 3,
        "image": "https://wp.scoopwhoop.com/wp-content/uploads/2014/09/5677315b6e510a6f3a759a81_7.jpg",
        "deliveryTime" : 20,
    },   
    {
        "id": 18,
        "foodType": "Rajasthani Food",
        "name": "Rajasthani-Kari",
        "price": 100,
        "rating": 3,
        "image": "https://wp.scoopwhoop.com/wp-content/uploads/2014/09/5677315b6e510a6f3a759a81_8.jpg",
        "deliveryTime" : 30,
    },   
    {
        "id": 19,
        "foodType": "Rajasthani Food",
        "name": "Gatte-ke-pulao",
        "price": 60,
        "rating": 4,
        "image": "https://wp.scoopwhoop.com/wp-content/uploads/2014/09/5677315b6e510a6f3a759a81_9.JPG",
        "deliveryTime" : 40,
    },   
    {
        "id": 20,
        "foodType": "Rajasthani Food",
        "name": "Churma-Ladoo",
        "price": 100,
        "rating": 5,
        "image": "https://wp.scoopwhoop.com/wp-content/uploads/2014/09/5677315b6e510a6f3a759a81_10.jpg",
        "deliveryTime" : 40,
    },   
    {
        "id": 21,
        "foodType": "Rajasthani Food",
        "name": "Methi Puri",
        "price": 60,
        "rating": 4,
        "image": "https://wp.scoopwhoop.com/wp-content/uploads/2014/09/5677315b6e510a6f3a759a81_13.jpg",
        "deliveryTime" : 50,
    },   
    {
        "id": 22,
        "foodType": "Rajasthani Food",
        "name": "Malwa Kachori",
        "price": 40,
        "rating": 5,
        "image": "https://wp.scoopwhoop.com/wp-content/uploads/2014/09/5677315b6e510a6f3a759a81_14.jpg",
        "deliveryTime" : 20,
    },   
    {
        "id": 23,
        "foodType": "Rajasthani Food",
        "name": "Payaz Kachori",
        "price": 20,
        "rating": 4,
        "image": "https://wp.scoopwhoop.com/wp-content/uploads/2014/09/5677315b6e510a6f3a759a81_15.jpg",
        "deliveryTime" : 20,
    },   
    {
        "id": 24,
        "foodType": "Rajasthani Food",
        "name": "Guzza",
        "price": 40,
        "rating": 2,
        "image": "https://wp.scoopwhoop.com/wp-content/uploads/2014/09/5677315b6e510a6f3a759a81_17.jpg",
        "deliveryTime" : 30,
    },      
    {
        "id": 25,
        "foodType": "Rajasthani Food",
        "name": "Gevar",
        "price": 140,
        "rating": 4,
        "image": "https://wp.scoopwhoop.com/wp-content/uploads/2014/09/5677315b6e510a6f3a759a81_19.JPG",
        "deliveryTime" : 30,
    },   
    {
        "id": 26,
        "foodType": "Chinese Food",
        "name": "Chow-Mein",
        "price": 60,
        "rating": 3,
        "image": "https://www.hotelmousai.com/blog/wp-content/uploads/2021/12/Chow-Mein.jpg",
        "deliveryTime" : 30,
    },   
    {
        "id": 27,
        "foodType": "Chinese Food",
        "name": "Spring Roll",
        "price": 60,
        "rating": 2,
        "image": "https://www.hotelmousai.com/blog/wp-content/uploads/2021/12/Spring-Rolls.jpg",
        "deliveryTime" : 20,
    },   
    {
        "id": 28,
        "foodType": "Chinese Food",
        "name": "Hakka-Noodle",
        "price": 100,
        "rating": 5,
        "image": "https://www.crazymasalafood.com/wp-content/images/20-most-favourite-chinese-dishes-of-india/hakka-noodles.jpg",
        "deliveryTime" : 40,
    },   
    {
        "id": 29,
        "foodType": "Chinese Food",
        "name": "Chilli-Paneer",
        "price": 60,
        "rating": 3,
        "image": "https://www.crazymasalafood.com/wp-content/images/20-most-favourite-chinese-dishes-of-india/chilli-paneer.jpg",
        "deliveryTime" : 30,
    },   
    {
        "id": 30,
        "foodType": "Chinese Food",
        "name": "Chilli-Potato",
        "price": 140,
        "rating": 5,
        "image": "https://www.crazymasalafood.com/wp-content/images/20-most-favourite-chinese-dishes-of-india/sesame-honey-chilli-potatoes.jpg",
        "deliveryTime" : 40,
    },   
    {
        "id": 31,
        "foodType": "Chinese Food",
        "name": "Manchurian",
        "price": 60,
        "rating": 4,
        "image": "https://www.myplantifulcooking.com/wp-content/uploads/2022/01/cabbage-manchurian-featured.jpg",
        "deliveryTime" : 40,
    },   
    {
        "id": 32,
        "foodType": "American Food",
        "name": "Sausage",
        "price": 180,
        "rating": 2,
        "image": "https://i.ndtvimg.com/i/2015-07/sausage-625_625x350_71435918358.jpg",
        "deliveryTime" : 50,
    },   
    {
        "id": 33,
        "foodType": "American Food",
        "name": "Cookies",
        "price": 40,
        "rating": 2,
        "image": "https://i.ndtvimg.com/i/2015-07/cookies_625x350_41435923489.jpg",
        "deliveryTime" : 20,
    },   
    {
        "id": 34,
        "foodType": "American Food",
        "name": "S'mores",
        "price": 140,
        "rating": 3,
        "image": "https://i.ndtvimg.com/i/2015-07/smores-625_625x350_81435923035.jpg",
        "deliveryTime" : 40,
    },   
    {
        "id": 35,
        "foodType": "American Food",
        "name": "Cronut",
        "price": 100,
        "rating": 5,
        "image": "https://i.ndtvimg.com/i/2015-07/cronut-625_625x350_71435922943.jpg",
        "deliveryTime" : 20,
    },   
    {
        "id": 36,
        "foodType": "American Food",
        "name": "Chicken & Waffles",
        "price": 100,
        "rating": 2,
        "image": "https://i.ndtvimg.com/i/2015-07/waffles-and-chicken-625_625x350_81435923012.jpg",
        "deliveryTime" : 40,
    },   
    {
        "id": 37,
        "foodType": "American Food",
        "name": "Pancakes",
        "price": 100,
        "rating": 3,
        "image": "https://i.ndtvimg.com/i/2015-07/pancakes-625_625x350_71435918903.jpg",
        "deliveryTime" : 30,
    },   
    {
        "id": 38,
        "foodType": "American Food",
        "name": "Mac & Cheese",
        "price": 140,
        "rating": 4,
        "image": "https://i.ndtvimg.com/i/2015-07/america-food_624x350_71435923721.jpg",
        "deliveryTime" : 20,
    },   
    {
        "id": 39,
        "foodType": "American Food",
        "name": "Hot Dogs",
        "price": 180,
        "rating": 3,
        "image": "https://i.ndtvimg.com/i/2015-07/hot-dog-625_625x350_51435919105.jpg",
        "deliveryTime" : 50,
    },   
    {
        "id": 40,
        "foodType": "American Food",
        "name": "Burger",
        "price": 100,
        "rating": 5,
        "image": "https://i.ndtvimg.com/i/2015-07/burger-625_625x350_51435922877.jpg",
        "deliveryTime" : 50,
    },      
    {
        "id": 41,
        "foodType": "Italian Food",
        "name": "Caprese Salad",
        "price": 140,
        "rating": 3,
        "image": "https://i.ndtvimg.com/i/2017-09/caprese-salad_625x350_51506417724.jpg",
        "deliveryTime" : 40,
    },   
    {
        "id": 42,
        "foodType": "Italian Food",
        "name": "Bruschetta",
        "price": 60,
        "rating": 3,
        "image": "https://i.ndtvimg.com/i/2017-09/bruschetta_625x350_71506417841.jpg",
        "deliveryTime" : 50,
    },   
    {
        "id": 43,
        "foodType": "Italian Food",
        "name": "Pasta Carbonara",
        "price": 100,
        "rating": 4,
        "image": "https://i.ndtvimg.com/i/2017-09/pasta-carbonara_600x300_41506417953.jpg",
        "deliveryTime" : 40,
    },   
    {
        "id": 44,
        "foodType": "Italian Food",
        "name": "Pizza",
        "price": 180,
        "rating": 5,
        "image": "https://i.ndtvimg.com/i/2017-09/margherita-pizza_600x300_51506418004.jpg",
        "deliveryTime" : 50,
    },   
    {
        "id": 45,
        "foodType": "Italian Food",
        "name": "Mushroom",
        "price": 140,
        "rating": 2,
        "image": "https://i.ndtvimg.com/i/2017-09/risotto_625x350_81506418041.jpg",
        "deliveryTime" : 30,
    },   
    {
        "id": 46,
        "foodType": "Italian Food",
        "name": "Pasta",
        "price": 100,
        "rating": 4,
        "image": "https://i.ndtvimg.com/i/2017-09/pasta-con-pomodoro-e-basilico_625x350_51506418092.jpg",
        "deliveryTime" : 40,
    },   
    {
        "id": 47,
        "foodType": "Italian Food",
        "name": "Lasagna",
        "price": 180,
        "rating": 4,
        "image": "https://i.ndtvimg.com/i/2017-10/lasagna_620x350_81508846322.jpg",
        "deliveryTime" : 30,
    },
    {
        "id": 48,
        "foodType": "Italian Food",
        "name": "Pasta Special",
        "price": 180,
        "rating": 5,
        "image": "https://images.pexels.com/photos/803963/pexels-photo-803963.jpeg?cs=srgb&dl=pexels-eneida-nieves-803963.jpg&fm=jpg",
        "deliveryTime" : 40,
    }
]